import { calcularPromedio } from "./ejercicio1/ejercicio1.js";
import { calcularInventario } from "./ejercicio2/ejercicio2.js";
import { calcularPromedioo } from "./ejercicio3/ejercicio3.js";
import { ordenarProductos } from "./ejercicio4/ejercicio4.js";
import { validarUsuario } from "./ejercicio5/ejercicio5.js";
import { calcularSalarioBase, calcularDeducciones, calcularNeto } from "./ejercicio6/ejercicio6.js";
import { registrarProductos } from "./ejercicio7/ejercicio7.js";
import { buscarCursos } from "./ejercicio8/ejercicio8.js";
import { procesarPagos } from "./ejercicio9/ejercicio9.js";
import { fusionarUsuarios } from "./ejercicio10/ejercicio10.js";
import { generarResumen } from "./ejercicio11/ejercicio11.js";
import { seleccionarPaciente } from "./ejercicio12/ejercicio12.js";
import { analizarGastos } from "./ejercicio13/ejercicio13.js";
import { filtrarActivos, contarParticipantes, evaluarProyecto } from "./ejercicio14/ejercicio14.js";
import { generarRecomendaciones } from "./ejercicio15/ejercicio15.js";
import { analizarUsuarios } from "./ejercicio16/ejercicio16.js";
import { procesarInventario } from "./ejercicio17/ejercicio17.js";

export * from "./ejercicio1/ejercicio1.js";
export * from "./ejercicio2/ejercicio2.js";
export * from "./ejercicio3/ejercicio3.js";
export * from "./ejercicio4/ejercicio4.js";
export * from "./ejercicio5/ejercicio5.js";
export * from "./ejercicio6/ejercicio6.js";
export * from "./ejercicio7/ejercicio7.js";
export * from "./ejercicio8/ejercicio8.js";
export * from "./ejercicio9/ejercicio9.js";
export * from "./ejercicio10/ejercicio10.js";
export * from "./ejercicio11/ejercicio11.js";
export * from "./ejercicio12/ejercicio12.js";
export * from "./ejercicio13/ejercicio13.js";
export * from "./ejercicio14/ejercicio14.js";
export * from "./ejercicio15/ejercicio15.js";
export * from "./ejercicio16/ejercicio16.js";
export * from "./ejercicio17/ejercicio17.js";